"""
refactor: enhance database models and establish clear relationships

- Added  field to Enrollment model to manage course access.
- Linked Payment model to Course and Enrollment for better tracking.
- Implemented  on Enrollment to prevent duplicate subscriptions.
- Added  methods to all models for easier debugging in terminal.
- Updated relationships with appropriate  for Users and Courses.

Revision ID: aec66023daba
Revises: a3602f59b54f
Create Date: 2026-04-14 17:45:25.505185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec66023daba'
down_revision = 'a3602f59b54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('unique_user_course_enrollment', ['user_id', 'course_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('enrollment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'enrollments', ['enrollment_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enrollment_id')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_course_enrollment', type_='unique')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
